# must do conda install -c alexxfernandez13 bienes_inmuebles
package:
  name: bienes_inmuebles
  version: 1.1

about:
  home: https://github.com/alexxfernandez13/bienes_inmuebles
  license: Apache
  license_file: LICENSE
  summary: Tool for predicting real estate prices

source:
  path: ../

build:
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    # Base dependencies
    - numpy
    - matplotlib=3.3.2
    - scipy
    - pandas
    - scikit-learn
    - pytest
    - joblib
    - colorama


test:
  imports:
    - bienes_inmuebles